;;;; examples/core-image.lisp -- image generation and filtering, headless.
;;;;
;;;; Core Image is a filter graph: every filter takes a CIImage and parameters
;;;; and produces another CIImage, and nothing is computed until something asks
;;;; for pixels.  That is a good fit for a REPL -- build the graph, look at it,
;;;; change one parameter, look again -- and it needs no window server, so it
;;;; runs anywhere and is testable in CI.
;;;;
;;;; Everything here is self-contained: the images are GENERATED by Core Image
;;;; rather than read from disk, so the example ships no assets and the tests
;;;; depend on nothing.  A checkerboard, a gradient and a QR code are three
;;;; filters away from nothing at all.
;;;;
;;;; Three things it shows that the other examples do not:
;;;;
;;;;   Filters are configured by KEY, not by selector.  -setValue:forKey: with a
;;;;   string key is how the whole framework is driven, so the bridge work is
;;;;   boxing Lisp values into the objects Core Image expects -- which is what
;;;;   OBJC-VALUE below does, and why it exists.
;;;;
;;;;   A generator's output is INFINITE in extent, and asking an infinite image
;;;;   for pixels gets you nothing.  Every generator here is cropped before it
;;;;   is rendered.  This is the mistake that produces an empty PNG and no error.
;;;;
;;;;   Framework constants are read from the framework.  kCIFormatRGBA8 is 264,
;;;;   which is not a number worth guessing -- and guessing is tempting because
;;;;   a wrong value here still produces a plausible-looking PNG.

(in-package #:objc/examples)

(defparameter +core-image-frameworks+
  '("/System/Library/Frameworks/CoreImage.framework/CoreImage"
    "/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics"))

(defun ensure-core-image ()
  (objc:ensure-objc-initialized :modules +core-image-frameworks+))

(cffi:defcfun ("CGColorSpaceCreateDeviceRGB" %device-rgb-color-space) :pointer)
(cffi:defcfun ("CGColorSpaceRelease" %release-color-space) :void (space :pointer))

(defun ci-format (name)
  "The value of a CIFormat constant, read from CoreImage rather than guessed.

    (ci-format \"kCIFormatRGBA8\")   ;; => 264

These are exported integers, not an enumeration in a header this library can
see, and 264 is not a number anyone would arrive at by inference.  Worth reading
rather than hardcoding because a wrong format does not fail loudly -- it renders
something."
  (let ((symbol (cffi:foreign-symbol-pointer name)))
    (unless symbol
      (error "No such CoreImage constant: ~A" name))
    (cffi:mem-ref symbol :int)))

;;; Boxing Lisp values for -setValue:forKey: -----------------------------------

(defun objc-value (value)
  "VALUE as something Core Image will accept from -setValue:forKey:.

A filter parameter is an object: a number has to become an NSNumber, a
geometric parameter a CIVector, a colour a CIColor.  Strings and objects pass
through -- INVOKE already converts a Lisp string to an NSString."
  (typecase value
    (string value)
    (real (objc:invoke "NSNumber" "numberWithDouble:" (float value 1d0)))
    ((vector * 4) (objc:invoke "CIVector" "vectorWithX:Y:Z:W:"
                               (float (aref value 0) 1d0) (float (aref value 1) 1d0)
                               (float (aref value 2) 1d0) (float (aref value 3) 1d0)))
    ((vector * 2) (objc:invoke "CIVector" "vectorWithX:Y:"
                               (float (aref value 0) 1d0) (float (aref value 1) 1d0)))
    (t value)))

(defun rgba (red green blue &optional (alpha 1d0))
  "A CIColor, for filter parameters that want one."
  (ensure-core-image)
  (objc:invoke "CIColor" "colorWithRed:green:blue:alpha:"
               (float red 1d0) (float green 1d0) (float blue 1d0) (float alpha 1d0)))

;;; The graph ------------------------------------------------------------------

(defun apply-filter (name &rest parameters)
  "Build the filter NAME with PARAMETERS and return its output CIImage.

PARAMETERS are key/value pairs using Core Image's own key strings:

    (apply-filter \"CIGaussianBlur\" \"inputImage\" image \"inputRadius\" 8)

Every filter in the framework is reachable this way; -setValue:forKey: is the
whole interface.  (objc/examples:filter-names) lists them."
  (ensure-core-image)
  (let ((filter (objc:invoke "CIFilter" "filterWithName:" name)))
    (when (cffi:null-pointer-p (objc:objc-object-pointer filter))
      (error "No such Core Image filter: ~A" name))
    (objc:invoke filter "setDefaults")
    (loop for (key value) on parameters by #'cddr
          do (objc:invoke filter "setValue:forKey:" (objc-value value) key))
    (objc:invoke filter "outputImage")))

(defun filter-names (&optional (category "CICategoryBuiltIn"))
  "Every filter Core Image knows about, as strings."
  (ensure-core-image)
  (objc:with-autorelease-pool ()
    (let ((names (objc:invoke "CIFilter" "filterNamesInCategory:" category)))
      (loop for i below (objc:invoke names "count")
            collect (objc:ns-string-to-string
                     (objc:invoke names "objectAtIndex:" i))))))

(defun crop (image rect)
  "Limit IMAGE to RECT, given as #(x y width height).

A generator produces an image of INFINITE extent, and rendering one of those
gives an empty result rather than an error.  Cropping is not decoration here; it
is what makes the image renderable at all.  RECT crosses as a CGRect by value."
  (objc:invoke image "imageByCroppingToRect:"
               (map 'vector (lambda (n) (float n 1d0)) rect)))

(defun scale (image factor)
  "Scale IMAGE by FACTOR, resampling.

CILanczosScaleTransform rather than -imageByApplyingTransform: because it
RESAMPLES -- a transform moves the sampling grid and leaves the filter chain to
interpolate, which is not the same picture.  Use TRANSFORM below when the affine
matrix is what you want.

An earlier version of this comment said -imageByApplyingTransform: was out of
reach because CGAffineTransform is \"a struct this library has no layout for\".
That was wrong, and TRANSFORM exists partly to say so: the layout arrives inline
in the method encoding -- {CGAffineTransform=dddddd} -- so RESOLVE-STRUCT-LAYOUT
never has to look one up, and a 48-byte buffer crosses like any other structure."
  (apply-filter "CILanczosScaleTransform" "inputImage" image "inputScale" factor))

;;; Affine transforms --------------------------------------------------------------
;;;
;;; DEFINE-OBJC-STRUCT is the library's way to name a C structure's fields, and
;;; outside the manual's own two-float `pair' nothing here had used it.  A
;;; CGAffineTransform is the natural case: six doubles that mean something
;;; individually, passed by value to a real framework method.
;;;
;;;     | a  b  0 |
;;;     | c  d  0 |
;;;     | tx ty 1 |
;;;
;;; Note the library needs no layout table entry for this.  The encoding the
;;; runtime hands back carries the field list inline, which is true of any
;;; structure a framework's own method signature mentions; *STRUCT-LAYOUT-OVERRIDES*
;;; is for the ones whose layout the runtime elides.

(objc:define-objc-struct (affine-transform (:foreign-name "CGAffineTransform"))
  (:a :double) (:b :double)
  (:c :double) (:d :double)
  (:tx :double) (:ty :double))

(defun make-transform (&key (a 1) (b 0) (c 0) (d 1) (tx 0) (ty 0))
  "A CGAffineTransform as a foreign buffer.  The caller frees it, or uses
WITH-TRANSFORM."
  (let ((buffer (cffi:foreign-alloc :double :count 6)))
    (loop for value in (list a b c d tx ty)
          for i from 0
          do (setf (cffi:mem-aref buffer :double i) (float value 1d0)))
    buffer))

(defmacro with-transform ((var &rest arguments) &body body)
  `(let ((,var (make-transform ,@arguments)))
     (unwind-protect (locally ,@body)
       (cffi:foreign-free ,var))))

(defun transform-values (transform)
  "The six fields of TRANSFORM as a list, in order."
  (loop for i below 6 collect (cffi:mem-aref transform :double i)))

(defun scaling (x &optional (y x))
  (make-transform :a x :d y))

(defun translation (x y)
  (make-transform :tx x :ty y))

(defun rotation (radians)
  (let ((cosine (cos radians)) (sine (sin radians)))
    (make-transform :a cosine :b sine :c (- sine) :d cosine)))

(defun transform (image matrix)
  "IMAGE with MATRIX applied -- moved, scaled or rotated, not resampled.

    (with-transform (m :a 2 :d 2) (transform (checkerboard) m))

The matrix crosses BY VALUE, forty-eight bytes of it."
  (objc:invoke image "imageByApplyingTransform:" matrix))

(defun image-extent (image)
  "IMAGE's extent as #(x y width height), rounded."
  (map 'vector #'round (objc:invoke image "extent")))

;;; Rendering ------------------------------------------------------------------

(defun render-png (image &key path (rect nil))
  "Render IMAGE and return the PNG bytes, writing them to PATH when given.

RECT crops first, and is required for anything a generator produced."
  (ensure-core-image)
  (objc:with-autorelease-pool ()
    (let* ((image (if rect (crop image rect) image))
           (context (objc:invoke "CIContext" "context"))
           (space (%device-rgb-color-space)))
      (unwind-protect
           (let ((data (objc:invoke context
                                    "PNGRepresentationOfImage:format:colorSpace:options:"
                                    image (ci-format "kCIFormatRGBA8") space
                                    (objc:invoke "NSDictionary" "dictionary"))))
             (when (cffi:null-pointer-p (objc:objc-object-pointer data))
               (error "Core Image rendered nothing.  An image of infinite extent ~
                       -- anything a generator produced and nothing cropped -- ~
                       is the usual reason."))
             (let ((bytes (ns-data-to-bytes data)))
               (when path
                 (with-open-file (out path :direction :output
                                           :element-type '(unsigned-byte 8)
                                           :if-exists :supersede)
                   (write-sequence bytes out)))
               bytes))
        (%release-color-space space)))))

(defun png-p (bytes)
  "True when BYTES begins with the PNG signature."
  (and (>= (length bytes) 8)
       (equalp (subseq bytes 0 8) #(137 80 78 71 13 10 26 10))))

;;; Things worth making --------------------------------------------------------

(defun checkerboard (&key (size 256) (square 32) (color-0 (rgba 0 0 0))
                          (color-1 (rgba 1 1 1)))
  "A checkerboard, cropped to SIZE by SIZE."
  (crop (apply-filter "CICheckerboardGenerator"
                      "inputColor0" color-0 "inputColor1" color-1
                      "inputWidth" square "inputCenter" (vector 0 0))
        (vector 0 0 size size)))

(defun gradient (&key (size 256) (from (rgba 0 0 1)) (to (rgba 1 0.5 0)))
  "A linear gradient, cropped to SIZE by SIZE."
  (crop (apply-filter "CILinearGradient"
                      "inputPoint0" (vector 0 0) "inputColor0" from
                      "inputPoint1" (vector size size) "inputColor1" to)
        (vector 0 0 size size)))

(defun qr-code (text &key (scale 8) (correction "M"))
  "A QR code for TEXT, as a CIImage scaled up by SCALE.

The generator produces one pixel per module, so it needs scaling to be usable --
which is the same crop-and-scale discipline the rest of this file is about.
CORRECTION is \"L\", \"M\", \"Q\" or \"H\", least to most redundant."
  (ensure-core-image)
  (let* ((data (objc:invoke (objc:invoke "NSString" "stringWithUTF8String:" text)
                            "dataUsingEncoding:" 4)) ; NSUTF8StringEncoding
         (image (apply-filter "CIQRCodeGenerator"
                              "inputMessage" data
                              "inputCorrectionLevel" correction)))
    (if (> scale 1) (scale image scale) image)))

;;; A worked example -----------------------------------------------------------

(defun test-core-image (&key path)
  "Generate, filter and render, and return a plist of what happened.

    (objc/examples:test-core-image)
    => (:FILTERS 247 :FORMAT 264 :CHECKERBOARD T :BLURRED T :GRADIENT T :QR T
        :QR-DECODES T :TRANSFORMED ((0 0 128 128) (10 20 64 64)) :INFINITE-REFUSED T)

Three of these earn their place.  :TRANSFORMED passes a CGAffineTransform BY
VALUE -- forty-eight bytes, six doubles -- and checks the extent it produces: a
scale of two doubles the size, and a translation moves the origin without
changing it.  Getting the matrix across wrong would give neither.

  :INFINITE-REFUSED, because rendering a
generator's output without cropping produces nothing, and this asserts we report
that rather than returning an empty PNG.  And :QR-DECODES, because it is the
difference between \"those are plausible PNG bytes\" and \"that is a QR code\":
Vision reads the rendered image back and the payload has to match.  Nothing else
here checks that a filter graph produced the picture it was asked for."
  (ensure-core-image)
  (objc:with-autorelease-pool ()
    (let* ((board (checkerboard))
           (blurred (apply-filter "CIGaussianBlur" "inputImage" board "inputRadius" 6))
           (board-png (render-png board))
           (blur-png (render-png blurred :rect #(0 0 256 256)))
           (gradient-png (render-png (gradient)))
           (qr-text "https://github.com/lispnik/objc")
           (qr-png (render-png (qr-code qr-text) :path path)))
      (list :filters (length (filter-names))
            :format (ci-format "kCIFormatRGBA8")
            :checkerboard (and (png-p board-png) (> (length board-png) 100))
            :blurred (and (png-p blur-png) (/= (length blur-png) (length board-png)))
            :gradient (png-p gradient-png)
            :qr (and (png-p qr-png) (> (length qr-png) 100))
            :qr-decodes (equal (list qr-text) (read-barcodes qr-png))
            :transformed
            (let ((square (checkerboard :size 64 :square 8)))
              (list (with-transform (m :a 2 :d 2)
                      (coerce (image-extent (transform square m)) 'list))
                    (with-transform (m :tx 10 :ty 20)
                      (coerce (image-extent (transform square m)) 'list))))
            :infinite-refused
            (handler-case
                (progn (render-png (apply-filter "CICheckerboardGenerator")) nil)
              (error () t))))))

(defun report-core-image (&optional (directory (uiop:temporary-directory)))
  "Write a checkerboard, a gradient and a QR code, and say where they went."
  (ensure-core-image)
  (flet ((out (name) (merge-pathnames name directory)))
    (let ((files (list (cons "objc-checkerboard.png" (checkerboard))
                       (cons "objc-gradient.png" (gradient))
                       (cons "objc-qr.png" (qr-code "https://github.com/lispnik/objc")))))
      (loop for (name . image) in files
            for path = (out name)
            do (format t "~&~D bytes -> ~A~%"
                       (length (render-png image :path path)) path))
      (format t "~D built-in filters available~%" (length (filter-names))))))
